import pandas as pd, numpy as np
pd.set_option('display.max_columns', None)
pd.set_option('display.width', 200)

base = 'data'
train = pd.read_csv(f'{base}/train.csv')
test = pd.read_csv(f'{base}/test.csv')
stores = pd.read_csv(f'{base}/stores.csv')
oil = pd.read_csv(f'{base}/oil.csv')
holidays = pd.read_csv(f'{base}/holidays_events.csv')
transactions = pd.read_csv(f'{base}/transactions.csv')
sub = pd.read_csv(f'{base}/sample_submission.csv')

print('=== TRAIN ===', train.shape)
print(train.head(3).to_string())
print('dtypes:', dict(train.dtypes))
print('date range:', train['date'].min(), '->', train['date'].max())
print('stores:', train['store_nbr'].nunique(), '| families:', train['family'].nunique())
print('sales NaN:', train['sales'].isna().sum(), '| onpromotion NaN:', train['onpromotion'].isna().sum())
print('target stats:\n', train['sales'].describe())
print()
print('=== TEST ===', test.shape)
print(test.head(3).to_string())
print('date range test:', test['date'].min(), '->', test['date'].max())
print()
print('=== STORES ===', stores.shape)
print(stores.head().to_string())
print('city', stores['city'].nunique(), '| state', stores['state'].nunique(), '| type', stores['type'].nunique())
print()
print('=== OIL ===', oil.shape, '| dates:', oil['date'].min(), '->', oil['date'].max())
print('=== HOLIDAYS ===', holidays.shape)
print(holidays['type'].value_counts().to_dict())
print('=== TRANSACTIONS ===', transactions.shape)
print('=== SAMPLE SUB ===', sub.shape)
print(sub.head(2).to_string())
print('n lignes submission attendues:', len(sub))
